import Link from "next/link";
import { ArrowRight, BookOpen, BrainCircuit, Sparkles } from "lucide-react";
import { OfficialLogo } from "@/components/brand/official-logo";

export function LandingPage() {
  return <main className="landing-page"><header className="landing-header"><Link href="/" aria-label="AryaVerse"><OfficialLogo className="h-auto w-44" priority /></Link><nav className="hidden items-center gap-6 text-sm text-[var(--text-secondary)] sm:flex"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><Link href="/login" className="font-semibold text-[var(--accent-strong)]">Entrar</Link></nav></header><section className="landing-hero"><div className="landing-hero-copy"><p className="landing-kicker"><Sparkles size={16} />UM UNIVERSO PARA APRENDER</p><h1>Estude com mais calma, clareza e continuidade.</h1><p className="landing-lead">O AryaVerse transforma matérias, revisões e descobertas em uma jornada pessoal de conhecimento.</p><div className="flex flex-wrap gap-3"><Link href="/cadastro" className="landing-primary">Começar minha jornada <ArrowRight size={17} /></Link><Link href="/login" className="landing-secondary">Já tenho uma conta</Link></div></div><div className="landing-book-scene" aria-hidden><div className="landing-glow" /><BookOpen className="landing-book-icon" size={104} strokeWidth={1.1} /><span className="landing-orbit landing-orbit-one" /><span className="landing-orbit landing-orbit-two" /></div></section><section id="como-funciona" className="landing-section"><p className="landing-kicker">UM CAMINHO QUE ACOMPANHA VOCÊ</p><h2>Conhecimento fica mais vivo quando encontra um lugar.</h2><div id="recursos" className="landing-cards"><Feature icon={BookOpen} title="Organize" text="Crie matérias, capítulos e uma biblioteca que cresce junto com você." /><Feature icon={BrainCircuit} title="Compreenda" text="Use resumos, mapas mentais, flashcards e avaliações para aprofundar cada ideia." /><Feature icon={Sparkles} title="Continue" text="Acompanhe suas jornadas, registre descobertas e retome de onde parou." /></div></section><footer className="landing-footer"><span>AryaVerse</span><span>Seu universo de estudos.</span></footer></main>;
}

function Feature({ icon: Icon, title, text }: { icon: typeof BookOpen; title: string; text: string }) { return <article className="landing-card"><Icon size={24} /><h3>{title}</h3><p>{text}</p></article>; }
