import Link from "next/link";
import { ArrowRight, BookOpen, Clock3, Sprout, TrendingUp } from "lucide-react";
import type { DashboardData } from "./dashboard-data";

export function DashboardSnapshot({ data }: { data: DashboardData }) {
  const latest = data.subjects[0];
  return <section className="dashboard-snapshot mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><article className="settings-surface p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-[var(--accent)]">VISÃO GERAL</p><h2 className="mt-1 font-serif text-2xl">{data.subjects.length ? "Seu universo está ganhando forma." : "Tudo começa com uma primeira página."}</h2></div><TrendingUp className="text-[var(--accent-strong)]" /></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric icon={Clock3} label="Tempo" value="0 min" /><Metric icon={BookOpen} label="Capítulos" value={String(data.chapterCount)} /><Metric icon={Sprout} label="Livros" value={String(data.subjects.length)} />{data.averageScore !== null && <Metric icon={TrendingUp} label="Nota média" value={data.averageScore.toFixed(1).replace(".", ",")} />}</div>{latest ? <div className="mt-6 rounded-2xl bg-[var(--surface-soft)] p-4"><p className="text-sm font-semibold">Biblioteca em crescimento</p><p className="mt-1 text-sm text-[var(--text-secondary)]">{latest.name} · {latest.chapters} capítulo{latest.chapters === 1 ? "" : "s"} criado{latest.chapters === 1 ? "" : "s"}</p></div> : <Link href="/biblioteca" className="mt-6 block rounded-2xl bg-[var(--surface-soft)] p-4 text-sm font-semibold text-[var(--accent-strong)]">Criar minha primeira matéria <ArrowRight className="ml-1 inline" size={15} /></Link>}</article><article className="settings-surface p-6"><h2 className="font-serif text-2xl">Últimas atividades</h2>{data.activities.length ? <ul className="mt-4 space-y-3">{data.activities.map((activity) => <li key={activity.id} className="border-b border-[var(--border)] pb-3 text-sm text-[var(--text-secondary)] last:border-0">{activity.detail}</li>)}</ul> : <p className="mt-4 rounded-2xl bg-[var(--surface-soft)] p-4 text-sm leading-6 text-[var(--text-secondary)]">Suas atividades aparecerão aqui conforme você estudar.</p>}<div className="mt-5 flex gap-3"><Link href="/jardim-das-aguas" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent-strong)]">Resumo do Jardim <ArrowRight size={15} /></Link><Link href="/biblioteca" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent-strong)]">Biblioteca <ArrowRight size={15} /></Link></div></article></section>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="rounded-2xl bg-[var(--surface-soft)] p-3"><Icon size={17} className="text-[var(--accent)]" /><span className="mt-3 block text-lg font-semibold">{value}</span><small className="text-[var(--text-muted)]">{label}</small></div>; }
