export type SummaryStyle = "short" | "complete" | "bullets" | "notebook" | "technical" | "simple";
export type ChapterStatus = "draft" | "ready" | "processing" | "failed";
export type SubjectRecord = { id: string; name: string; description?: string; coverColor: string; icon: string; visualTheme: string; weeklyGoal?: number; archived: boolean; createdAt: string; updatedAt: string };
export type StudyBookType = "normal" | "final_assessment";
export type StudyBookRecord = { id: string; subjectId: string; title: string; bookType: StudyBookType; createdAt: string; updatedAt: string };
export type ChapterRecord = { id: string; subjectId: string; bookId?: string; title: string; originalText: string; summaryStyle: SummaryStyle; notes?: string; status: ChapterStatus; createdAt: string; updatedAt: string };
export type SummaryRecord = { id: string; chapterId: string; content: string; style: SummaryStyle; createdAt: string; updatedAt: string };
export type HighlightRecord = {
  id: string;
  chapterId: string;
  text: string;
  color: "yellow" | "pink" | "lilac" | "blue" | "green";
  start?: number;
  end?: number;
  /** Contextual anchors keep a selection stable when React recreates text nodes. */
  prefix?: string;
  suffix?: string;
  summaryArtifactId?: string;
  status?: "active" | "orphaned";
  label?: string;
  note?: string;
  createdAt: string;
  updatedAt?: string;
};
export type ActivityDestination = "content" | "summary" | "flashcards" | "quiz" | "questions" | "mind-map" | "keywords" | "explanation" | "notes" | "history";
export type ActivityHistory = { id: string; chapterId: string; type: string; detail: string; createdAt: string; destination?: ActivityDestination; resourceId?: string; sourceText?: string };
export type ChapterArtifactType = "summary" | "flashcards" | "quiz" | "questions" | "mind-map" | "keywords" | "explanation";
export type ChapterArtifact = { id: string; chapterId: string; type: ChapterArtifactType; content: string; sourceText?: string; sourceArea?: "content" | "summary"; createdAt: string };
export type FlashcardReview = { id: string; chapterId: string; artifactId: string; cardIndex: number; status: "known" | "review" | "forgot"; updatedAt: string };
export type User = { id: string; name: string; email: string; createdAt: string };
export type Note = { id: string; chapterId: string; content: string; highlightId?: string; createdAt: string; updatedAt: string };
export type Attachment = { id: string; chapterId: string; name: string; type: string; size: number; createdAt: string };
export type QuizOption = "A" | "B" | "C" | "D" | "E";
export type QuizQuestionType = "multiple_choice" | "statements" | "true_false_sequence" | "assertion_reason" | "association" | "application";
export type AssociationItem = { id: string; text: string };
export type QuizQuestion = { id: string; question: string; options: Record<QuizOption, string>; correctAnswer: QuizOption; explanation: string; sourceText?: string; sourceSection?: string; /** Optional to preserve quizzes created before question formats were tracked. */ questionType?: QuizQuestionType; statements?: string[]; assertion?: string; reason?: string; reasonJustifies?: boolean; associationLeft?: AssociationItem[]; associationRight?: AssociationItem[]; scenario?: string };
export type Quiz = { id: string; chapterId: string; questions: QuizQuestion[]; createdAt: string; sourceSummaryId?: string };
export type UserAnswer = { questionId: string; answer: QuizOption };
export type QuizAttempt = { id: string; quizId: string; chapterId: string; questionIds: string[]; answers: UserAnswer[]; startedAt: string; completedAt?: string; score?: number; markedForReview: string[] };
export type DiaryEntry = { id: string; title: string; content: string; color: "aqua" | "sapphire" | "pearl" | "lilac" | "gold"; createdAt: string; updatedAt: string; x: number; y: number; width: number; height: number };
export type FinalAssessmentRecord = { id: string; subjectId: string; bookId: string; bookType: "final_assessment"; title: "PROVA AVALIATIVA FINAL"; sourceFingerprint?: string; generalReview?: string; quickReview?: string; flashcards?: string; quiz?: Quiz; createdAt: string; updatedAt: string };
export type BookAssessmentRecord = { id: string; subjectId: string; bookId: string; title: "AVALIAÇÃO GERAL DO LIVRO"; sourceFingerprint?: string; generalReview?: string; quickReview?: string; flashcards?: string; quiz?: Quiz; createdAt: string; updatedAt: string };
