"use client";

import { Check, Sparkles } from "lucide-react";
import { useState } from "react";
import { themes, useTheme } from "@/components/theme/theme-provider";

export function AppearanceSettings() {
  const { theme, setTheme, reduceMotion, setReduceMotion } = useTheme();
  const [entryAnimation, setEntryAnimation] = useState(() => typeof window === "undefined" ? "always" : localStorage.getItem("arya-entry-animation") ?? "always");
  const changeEntryAnimation = (value: string) => { setEntryAnimation(value); localStorage.setItem("arya-entry-animation", value); };
  return <section><p className="text-sm font-medium text-[var(--accent)]">Seu refugio</p><h1 className="mt-1 font-serif text-3xl font-semibold">Aparencia e atmosfera</h1><p className="mt-3 max-w-xl text-[var(--text-secondary)]">Cada tema transforma seu universo inteiro: livros, jardim, Arya, superficies e caminhos.</p><div className="settings-surface mt-8 p-6"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[var(--glow)]" /><h2 className="font-semibold">Temas do AryaVerse</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{themes.map((item) => <button key={item.id} onClick={() => setTheme(item.id)} className={`theme-option ${theme === item.id ? "theme-option-active" : ""}`}><div className="theme-preview" data-preview={item.id}><i /><b /><span>Agir</span></div><div className="mt-3 flex items-center justify-between"><span className="font-semibold">{item.name}</span>{theme === item.id && <span className="grid size-5 place-items-center rounded-full bg-[var(--button-primary)] text-white"><Check size={13} /></span>}</div><small className="mt-1 block text-left text-[var(--text-muted)]">Aplicar esta atmosfera</small></button>)}</div></div><label className="settings-surface mt-6 flex items-center justify-between p-5"><span><span className="block font-semibold">Movimentos suaves</span><span className="mt-1 block text-sm text-[var(--text-secondary)]">Reduza particulas e transicoes quando quiser uma experiencia estatica.</span></span><input checked={!reduceMotion} onChange={(event) => setReduceMotion(!event.target.checked)} type="checkbox" className="size-5 accent-[var(--button-primary)]" /></label><label className="settings-surface mt-6 block p-5"><span className="block font-semibold">Entrada no AryaVerse</span><span className="mt-1 block text-sm text-[var(--text-secondary)]">Escolha quando deseja ver a passagem pelo livro-portal.</span><select value={entryAnimation} onChange={(event) => changeEntryAnimation(event.target.value)} className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm"><option value="always">Sempre mostrar</option><option value="once-session">Uma vez por sessão</option><option value="never">Nunca mostrar</option></select></label></section>;
}
