"use client";

import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Shuffle, Sparkles } from "lucide-react";
import { flashcardReviewRepository } from "@/services/repositories/flashcard-review-repository";
import { historyRepository } from "@/services/repositories/history-repository";
import type { ChapterArtifact } from "@/types/study-flow";

type Card = { front: string; back: string };
export function FlashcardDeck({ artifact, onStatus }: { artifact: ChapterArtifact; onStatus: (message: string) => void }) {
  const allCards = useMemo(() => parseCards(artifact.content), [artifact.content]); const [order, setOrder] = useState(() => allCards.map((_, index) => index)); const [position, setPosition] = useState(0); const [flipped, setFlipped] = useState(false); const [difficultOnly, setDifficultOnly] = useState(false); const [, refresh] = useState(0);
  const reviews = flashcardReviewRepository.list(artifact.id); const usableOrder = difficultOnly ? order.filter((index) => { const state = reviews.find((item) => item.cardIndex === index)?.status; return state === "review" || state === "forgot"; }) : order; const currentIndex = usableOrder[position] ?? usableOrder[0]; const card = allCards[currentIndex];
  function move(delta: number) { if (!usableOrder.length) return; setFlipped(false); setPosition((value) => (value + delta + usableOrder.length) % usableOrder.length); }
  function shuffle() { const next = [...order].sort(() => Math.random() - .5); setOrder(next); setPosition(0); setFlipped(false); onStatus("Cartas embaralhadas."); }
  function review(status: "known" | "review" | "forgot") { if (currentIndex === undefined) return; flashcardReviewRepository.save({ chapterId: artifact.chapterId, artifactId: artifact.id, cardIndex: currentIndex, status }); historyRepository.add(artifact.chapterId, "flashcard_reviewed", "Flashcard revisado", { destination: "flashcards", resourceId: artifact.id }); refresh((value) => value + 1); onStatus(status === "known" ? "Marcado como já sei." : status === "review" ? "Guardado para revisar." : "Guardado entre os cartões difíceis."); if (position < usableOrder.length - 1) move(1); }
  if (!allCards.length) return <p className="mt-6 text-sm text-[var(--text-secondary)]">Não foi possível reconhecer cartões nesta geração. Crie uma nova versão.</p>;
  if (!card) return <div className="mt-8 text-center"><p className="text-sm text-[var(--text-secondary)]">Ainda não há cartões difíceis marcados.</p><button onClick={() => { setDifficultOnly(false); setPosition(0); }} className="mt-3 text-sm font-semibold text-[var(--accent-strong)]">Ver todos os flashcards</button></div>;
  return <div className="mt-7"><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm font-semibold text-[var(--accent-strong)]">{position + 1} / {usableOrder.length}</span><div className="flex gap-2"><button onClick={shuffle} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm font-semibold"><Shuffle className="mr-1 inline" size={15} />Embaralhar</button><button onClick={() => { setDifficultOnly((value) => !value); setPosition(0); }} className={`rounded-full border px-3 py-2 text-sm font-semibold ${difficultOnly ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--border-strong)]"}`}>Revisar difíceis</button></div></div><div className="mx-auto mt-6 max-w-xl [perspective:1200px]"><button onClick={() => setFlipped((value) => !value)} className="group relative min-h-80 w-full [transform-style:preserve-3d] transition-transform duration-700" style={{ transform: flipped ? "rotateY(180deg)" : "rotateY(0deg)" }} aria-label="Virar flashcard"><CardFace className="[backface-visibility:hidden]" eyebrow="FRENTE" content={card.front} front /><CardFace className="absolute inset-0 [backface-visibility:hidden] [transform:rotateY(180deg)]" eyebrow="VERSO" content={card.back} /></button></div>{flipped && <div className="mx-auto mt-5 flex max-w-xl flex-wrap justify-center gap-2"><button onClick={() => review("known")} className="rounded-full bg-[var(--success)] px-4 py-2 text-sm font-semibold text-white">Já sei</button><button onClick={() => review("review")} className="rounded-full bg-[var(--button-primary)] px-4 py-2 text-sm font-semibold text-white">Preciso revisar</button><button onClick={() => review("forgot")} className="rounded-full border border-[var(--border-strong)] px-4 py-2 text-sm font-semibold">Não lembrei</button></div>}<div className="mx-auto mt-5 flex max-w-xl justify-between"><button onClick={() => move(-1)} className="inline-flex items-center gap-1 rounded-full border border-[var(--border-strong)] px-4 py-2 text-sm font-semibold"><ChevronLeft size={16} />Anterior</button><button onClick={() => move(1)} className="inline-flex items-center gap-1 rounded-full bg-[var(--button-primary)] px-4 py-2 text-sm font-semibold text-white">Próximo<ChevronRight size={16} /></button></div></div>;
}
function CardFace({ eyebrow, content, front, className = "" }: { eyebrow: string; content: string; front?: boolean; className?: string }) { return <article className={`flex min-h-80 w-full flex-col justify-between overflow-hidden rounded-[30px] border border-[var(--border)] bg-[var(--surface)] p-7 text-left shadow-[0_22px_45px_var(--shadow)] ${className}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[.18em] text-[var(--accent)]">{eyebrow}</span>{front && <span className="relative grid size-10 place-items-center"><span className="absolute size-8 rounded-[80%_20%_80%_20%] bg-[var(--accent-soft)] [transform:rotate(35deg)]" /><Sparkles className="relative text-[var(--accent-strong)]" size={17} /></span>}</div><p className="font-serif text-2xl leading-snug text-[var(--text-primary)]">{content}</p><span className="border-t border-[var(--border)] pt-4 text-xs text-[var(--text-muted)]">Toque para virar o cartão</span></article>; }
function parseCards(content: string): Card[] { return content.split(/\n+/).map((line) => { const [front, back] = line.replace(/^[-*]\s*/, "").split(/\s*\|\s*/); return { front: front?.replace(/^Frente:\s*/i, "").trim(), back: back?.replace(/^Verso:\s*/i, "").trim() }; }).filter((card) => card.front && card.back); }
