"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Circle, MapPin, Sparkles } from "lucide-react";
import { historyRepository } from "@/services/repositories/history-repository";
import { quizRepository } from "@/services/repositories/quiz-repository";
import type { Quiz, QuizAttempt, QuizOption, QuizQuestion } from "@/types/study-flow";
import { emitAryaEvent, emitAryaVisualPreference } from "@/components/arya/arya-state";
import { readApiJson } from "@/lib/utils";

type Props = { chapterId: string; originalText: string; summary: string; onStatus: (message: string) => void; onOpenSource?: (source?: string) => void; initialQuiz?: Quiz | null; generationEndpoint?: string; generationBody?: () => unknown; onQuizPrepared?: (quiz: Quiz) => void };
type QuizResponse = { questions?: Omit<QuizQuestion, "id">[]; error?: string };
const options: QuizOption[] = ["A", "B", "C", "D", "E"];

export function QuizWorkspace({ chapterId, originalText, summary, onStatus, onOpenSource, initialQuiz, generationEndpoint = "/api/ai/quiz", generationBody, onQuizPrepared }: Props) {
  const [quiz, setQuiz] = useState<Quiz | null>(() => initialQuiz ?? quizRepository.latest(chapterId)); const [attempt, setAttempt] = useState<QuizAttempt | null>(null); const [index, setIndex] = useState(0); const [generating, setGenerating] = useState(false); const [generationError, setGenerationError] = useState("");
  useEffect(() => () => emitAryaVisualPreference({ quiet: false }), []);
  async function prepare() { setGenerating(true); setGenerationError(""); emitAryaEvent("QUIZ_GENERATION_STARTED"); onStatus("Arya está preparando dez questões..."); try { const response = await fetch(generationEndpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(generationBody?.() ?? { originalText, summary }) }); const payload = await readApiJson<QuizResponse>(response); if (!response.ok || !payload.questions) throw new Error(payload.error ?? "Não foi possível preparar a avaliação."); const generated: Quiz = { id: crypto.randomUUID(), chapterId, createdAt: new Date().toISOString(), questions: payload.questions.map((question) => ({ ...question, id: crypto.randomUUID() })) }; const saved = onQuizPrepared ? generated : quizRepository.save(generated); onQuizPrepared?.(saved); historyRepository.add(chapterId, "quiz_created", "Avaliação com 10 questões preparada", { destination: "quiz", resourceId: saved.id }); setQuiz(saved); emitAryaEvent("QUIZ_GENERATED"); onStatus("Preparei dez questões para você."); } catch (error) { const message = error instanceof Error ? error.message : "Não foi possível preparar a avaliação."; setGenerationError(message); emitAryaEvent("ARYA_REQUEST_FAILED"); onStatus(message); } finally { setGenerating(false); } }
  function start(questionIds?: string[]) { if (!quiz) return; const next = quizRepository.startAttempt(quiz, questionIds); setAttempt(next); setIndex(0); emitAryaVisualPreference({ quiet: true }); if (questionIds) historyRepository.add(chapterId, "quiz_retried", "Quiz refeito com questões erradas", { destination: "quiz", resourceId: quiz.id }); onStatus(questionIds ? "Vamos revisar somente as questões que precisam de atenção." : "Sua avaliação começou. As respostas são salvas automaticamente."); }
  function answer(questionId: string, choice: QuizOption) { if (!attempt) return; const saved = quizRepository.saveAnswer(attempt.id, { questionId, answer: choice }); if (saved) setAttempt(saved); onStatus("Resposta salva."); }
  function finish() { if (!quiz || !attempt) return; if (attempt.answers.length !== attempt.questionIds.length) return onStatus("Responda todas as questões antes de finalizar."); if (!window.confirm("Finalizar a avaliação e ver a correção?")) return; const questions = quiz.questions.filter((question) => attempt.questionIds.includes(question.id)); const correct = questions.filter((question) => attempt.answers.find((answer) => answer.questionId === question.id)?.answer === question.correctAnswer).length; const score = Number(((correct / questions.length) * 10).toFixed(1)); const saved = quizRepository.complete(attempt.id, score); if (saved) setAttempt(saved); historyRepository.add(chapterId, "quiz_completed", `Quiz concluído — ${score}/10`, { destination: "quiz", resourceId: quiz.id }); emitAryaVisualPreference({ quiet: false }); emitAryaEvent(score >= 8 ? "QUIZ_COMPLETED_HIGH" : score >= 5 ? "QUIZ_COMPLETED_MEDIUM" : "QUIZ_COMPLETED_LOW"); onStatus("Avaliação corrigida e salva no histórico."); }
  if (!quiz) return <EmptyQuiz generating={generating} error={generationError} onPrepare={prepare} />; if (!attempt) return <ReadyQuiz quiz={quiz} onStart={() => start()} onPrepare={prepare} generating={generating} error={generationError} />; if (attempt.completedAt) return <QuizResult quiz={quiz} attempt={attempt} onRestart={() => start()} onRetryWrong={() => start(wrongIds(quiz, attempt))} onOpenSource={onOpenSource} />;
  const question = quiz.questions.find((item) => item.id === attempt.questionIds[index]); if (!question) return null; const selected = attempt.answers.find((answer) => answer.questionId === question.id)?.answer;
  return <section className="settings-surface mt-5 p-5 sm:p-7"><div className="flex items-center justify-between gap-3 text-sm text-[var(--text-secondary)]"><span>Questão {index + 1} de {attempt.questionIds.length}</span><span>{attempt.answers.length}/{attempt.questionIds.length} respondidas</span></div><div className="mt-3 h-1.5 rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${((index + 1) / attempt.questionIds.length) * 100}%` }} /></div><QuestionStructure question={question} /><div className="mt-5 grid gap-3">{options.map((option) => <button key={option} onClick={() => answer(question.id, option)} className={`rounded-2xl border p-4 text-left transition focus-visible:ring-2 focus-visible:ring-[var(--accent)] ${selected === option ? "border-[var(--accent-strong)] bg-[var(--accent-soft)]" : "border-[var(--border)] bg-[var(--surface-soft)]"}`}><strong className="mr-3">{option}.</strong>{question.options[option]}</button>)}</div><div className="mt-6 flex justify-between gap-2"><button disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="rounded-full border border-[var(--border-strong)] px-4 py-2 text-sm disabled:opacity-40">Anterior</button>{index < attempt.questionIds.length - 1 ? <button onClick={() => setIndex((value) => value + 1)} className="rounded-full bg-[var(--button-primary)] px-4 py-2 text-sm font-semibold text-white">Próxima</button> : <button onClick={finish} className="rounded-full bg-[var(--button-primary)] px-4 py-2 text-sm font-semibold text-white">Finalizar avaliação</button>}</div></section>;
}
function EmptyQuiz({ generating, error, onPrepare }: { generating: boolean; error: string; onPrepare: () => void }) { return <section className="settings-surface mt-5 p-8 text-center"><Sparkles className="mx-auto text-[var(--glow)]" /><h2 className="mt-3 font-serif text-2xl">Avalie este capítulo</h2><p className="mx-auto mt-2 max-w-lg text-sm text-[var(--text-secondary)]">Arya criará exatamente dez questões com alternativas de A a E, somente a partir do seu texto e resumo.</p>{error && <p role="alert" className="mx-auto mt-5 max-w-xl rounded-2xl border border-[var(--warning)] bg-[var(--surface-soft)] p-4 text-left text-sm leading-6 text-[var(--text-primary)]">{error}</p>}<button onClick={onPrepare} disabled={generating} className="mt-5 rounded-full bg-[var(--button-primary)] px-5 py-2.5 text-sm font-semibold text-white">{generating ? "Preparando avaliação..." : error ? "Tentar novamente" : "Preparar avaliação"}</button></section>; }
function ReadyQuiz({ quiz, onStart, onPrepare, generating, error }: { quiz: Quiz; onStart: () => void; onPrepare: () => void; generating: boolean; error: string }) { return <section className="settings-surface mt-5 p-6"><h2 className="font-serif text-2xl">Avaliação pronta</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{quiz.questions.length} questões aguardam suas respostas.</p>{error && <p role="alert" className="mt-4 rounded-2xl border border-[var(--warning)] bg-[var(--surface-soft)] p-4 text-sm leading-6">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={onStart} className="rounded-full bg-[var(--button-primary)] px-5 py-2.5 text-sm font-semibold text-white">Começar avaliação</button><button onClick={onPrepare} disabled={generating} className="rounded-full border border-[var(--border-strong)] px-5 py-2.5 text-sm font-semibold">{error ? "Tentar novamente" : "Gerar nova versão"}</button></div></section>; }
function QuizResult({ quiz, attempt, onRestart, onRetryWrong, onOpenSource }: { quiz: Quiz; attempt: QuizAttempt; onRestart: () => void; onRetryWrong: () => void; onOpenSource?: (source?: string) => void }) { const questions = quiz.questions.filter((question) => attempt.questionIds.includes(question.id)); const wrong = questions.filter((question) => attempt.answers.find((answer) => answer.questionId === question.id)?.answer !== question.correctAnswer); const correct = questions.length - wrong.length; const percent = Math.round((correct / questions.length) * 100); return <section className="settings-surface mt-5 p-5 sm:p-7"><div className="rounded-3xl bg-[var(--accent-soft)] p-6"><p className="text-sm font-semibold text-[var(--accent)]">RESULTADO</p><h2 className="mt-2 font-serif text-5xl">{attempt.score} / 10</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{percent}% · {correct} acertos · {wrong.length} erros</p></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={onRestart} className="rounded-full border border-[var(--border-strong)] px-4 py-2 text-sm font-semibold">Refazer completa</button>{wrong.length > 0 && <button onClick={onRetryWrong} className="rounded-full bg-[var(--button-primary)] px-4 py-2 text-sm font-semibold text-white">Refazer somente as que errei</button>}</div><div className="mt-7 space-y-4">{questions.map((question, index) => { const selected = attempt.answers.find((answer) => answer.questionId === question.id)?.answer; const isCorrect = selected === question.correctAnswer; return <article key={question.id} className="rounded-2xl bg-[var(--surface-soft)] p-5"><div className="flex gap-2"><span className={isCorrect ? "text-[var(--success)]" : "text-[var(--warning)]"}>{isCorrect ? <CheckCircle2 size={18} aria-label="Acertou" /> : <Circle size={18} aria-label="Errou" />}</span><div className="flex-1"><p className="font-semibold">Questão {index + 1} — {isCorrect ? "Acertou" : "Errou"}</p><p className="mt-2 text-sm">{question.question}</p><p className="mt-3 text-sm">Sua resposta: <strong>{selected ?? "Não respondida"}</strong></p><p className="mt-1 text-sm">Resposta correta: <strong>{question.correctAnswer}</strong></p><p className="mt-3 text-sm text-[var(--text-secondary)]">{question.explanation}</p><p className="mt-2 text-xs text-[var(--text-muted)]">Conceito: {question.sourceSection ?? "Trecho do material"}</p><button onClick={() => onOpenSource?.(question.sourceText)} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[var(--accent-strong)]"><MapPin size={15} />📚 Onde estudar isso</button></div></div></article>; })}</div></section>; }
function QuestionStructure({ question }: { question: QuizQuestion }) { return <div className="mt-7"><h2 className="font-serif text-2xl leading-snug">{question.question}</h2>{question.scenario && <p className="mt-4 rounded-2xl bg-[var(--surface-soft)] p-4 text-sm leading-7 text-[var(--text-secondary)]">{question.scenario}</p>}{question.statements && <ol className="mt-5 list-[upper-roman] space-y-2 pl-7 text-sm leading-7">{question.statements.map((statement, index) => <li key={index}>{statement}</li>)}</ol>}{question.assertion && <div className="mt-5 space-y-3 rounded-2xl border border-[var(--border)] p-4 text-sm leading-7"><p><strong>I.</strong> {question.assertion}</p><p className="text-center font-semibold tracking-[.16em] text-[var(--accent)]">PORQUE</p><p><strong>II.</strong> {question.reason}</p></div>}{question.associationLeft && <div className="mt-5 grid gap-4 md:grid-cols-2"><ListBlock title="Conceitos" items={question.associationLeft} /><ListBlock title="Definições" items={question.associationRight ?? []} /></div>}</div>; }
function ListBlock({ title, items }: { title: string; items: { id: string; text: string }[] }) { return <div className="rounded-2xl bg-[var(--surface-soft)] p-4"><p className="text-xs font-semibold tracking-[.12em] text-[var(--accent)]">{title}</p><ul className="mt-3 space-y-2 text-sm leading-6">{items.map((item) => <li key={item.id}><strong>{item.id}.</strong> {item.text}</li>)}</ul></div>; }
function wrongIds(quiz: Quiz, attempt: QuizAttempt) { return quiz.questions.filter((question) => attempt.questionIds.includes(question.id) && attempt.answers.find((answer) => answer.questionId === question.id)?.answer !== question.correctAnswer).map((question) => question.id); }
