"use client";

import { Copy, Eye, Pencil, Trash2 } from "lucide-react";
import { artifactRepository } from "@/services/repositories/artifact-repository";
import type { ChapterArtifact } from "@/types/study-flow";

export function SavedExplanations({ items, onRefresh, onOpenSource, onStatus }: { items: ChapterArtifact[]; onRefresh: () => void; onOpenSource: (item: ChapterArtifact) => void; onStatus: (message: string) => void }) {
  if (!items.length) return <section className="settings-surface mt-5 p-8 text-center"><h2 className="font-serif text-2xl">Explicações salvas</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Selecione um trecho em Conteúdo ou Resumo para pedir uma explicação à Arya.</p></section>;
  return <section className="settings-surface mt-5 p-5 sm:p-7"><header><p className="text-xs font-semibold tracking-[.15em] text-[var(--accent)]">ARYA EXPLICA</p><h2 className="mt-1 font-serif text-3xl">Explicações salvas</h2></header><div className="mt-6 space-y-4">{[...items].reverse().map((item) => <ExplanationCard key={item.id} item={item} onRefresh={onRefresh} onOpenSource={onOpenSource} onStatus={onStatus} />)}</div></section>;
}

function ExplanationCard({ item, onRefresh, onOpenSource, onStatus }: { item: ChapterArtifact; onRefresh: () => void; onOpenSource: (item: ChapterArtifact) => void; onStatus: (message: string) => void }) {
  return <details className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-5"><summary className="cursor-pointer list-none"><p className="text-xs font-semibold tracking-[.13em] text-[var(--accent)]">TRECHO EXPLICADO</p><p className="mt-2 line-clamp-2 font-medium">{item.sourceText ?? "Explicação geral do capítulo"}</p><time className="mt-2 block text-xs text-[var(--text-muted)]">{new Date(item.createdAt).toLocaleString("pt-BR")}</time></summary><ExplanationBody content={item.content} /><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => onOpenSource(item)} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm font-semibold"><Eye className="mr-1 inline" size={15} />Ver onde estudar isso</button><button onClick={() => navigator.clipboard.writeText(item.content).then(() => onStatus("Explicação copiada."))} className="rounded-full border border-[var(--border-strong)] p-2" aria-label="Copiar explicação"><Copy size={16} /></button><button onClick={() => { const content = window.prompt("Edite a explicação", item.content); if (content?.trim()) { artifactRepository.update(item.id, content.trim()); onRefresh(); onStatus("Explicação salva."); } }} className="rounded-full border border-[var(--border-strong)] p-2" aria-label="Editar explicação"><Pencil size={16} /></button><button onClick={() => { if (window.confirm("Excluir esta explicação salva?")) { artifactRepository.remove(item.id); onRefresh(); onStatus("Explicação excluída."); } }} className="rounded-full border border-[var(--border-strong)] p-2 text-red-700" aria-label="Excluir explicação"><Trash2 size={16} /></button></div></details>;
}
function ExplanationBody({ content }: { content: string }) { return <div className="mt-5 space-y-4 border-t border-[var(--border)] pt-5">{content.split(/\n(?=##\s)/).filter(Boolean).map((block, index) => { const [heading, ...body] = block.split("\n"); return <div key={`${heading}-${index}`}><h3 className="font-serif text-xl">{heading.replace(/^##\s*/, "")}</h3><p className="mt-2 whitespace-pre-wrap leading-7">{body.join("\n") || heading}</p></div>; })}</div>; }
