"use client";

import { useEffect, useRef, useState } from "react";
import { Copy, Expand, Highlighter, MessageCircle, Pencil, Save, Sparkles, StickyNote, X } from "lucide-react";
import { artifactRepository } from "@/services/repositories/artifact-repository";
import { highlightRepository } from "@/services/repositories/highlight-repository";
import { historyRepository } from "@/services/repositories/history-repository";
import type { ChapterArtifact, HighlightRecord } from "@/types/study-flow";
import { getSelectionAnchor, hasOverlap, resolveHighlight, type TextSelectionAnchor } from "./highlight-anchors";
import { emitAryaVisualPreference } from "@/components/arya/arya-state";

type Color = HighlightRecord["color"];
type Props = { chapterId: string; artifacts: ChapterArtifact[]; onStatus: (message: string) => void; onRegenerate: () => void; generating: boolean; onExplainSelection?: (text: string) => void };
const swatches: { color: Color; label: string; className: string }[] = [{ color: "yellow", label: "Amarelo", className: "bg-yellow-200" }, { color: "pink", label: "Rosa", className: "bg-pink-200" }, { color: "lilac", label: "Lilás", className: "bg-violet-200" }, { color: "blue", label: "Azul", className: "bg-sky-200" }, { color: "green", label: "Verde", className: "bg-emerald-200" }];

export function SummaryWorkspace({ chapterId, artifacts, onStatus, onRegenerate, generating, onExplainSelection }: Props) {
  const current = artifacts.at(-1);
  const [content, setContent] = useState(current?.content ?? ""); const [editing, setEditing] = useState(false); const [focus, setFocus] = useState(false); const [selection, setSelection] = useState<TextSelectionAnchor>(); const [active, setActive] = useState<HighlightRecord>(); const [panel, setPanel] = useState(false); const [, rerender] = useState(0); const readerRef = useRef<HTMLDivElement>(null);
  useEffect(() => () => emitAryaVisualPreference({ focus: false }), []);
  const highlights = highlightRepository.list(chapterId).map((item) => ({ ...item, ...resolveHighlight(content, item) }));
  if (!current) return <section className="settings-surface mt-5 p-8 text-center"><Sparkles className="mx-auto text-[var(--glow)]" /><h2 className="mt-3 font-serif text-2xl">Seu resumo vai nascer aqui.</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Arya utilizará somente o conteúdo deste capítulo.</p><button onClick={onRegenerate} disabled={generating} className="mt-5 rounded-full bg-[var(--button-primary)] px-5 py-2.5 text-sm font-semibold text-white">{generating ? "Arya está lendo..." : "Criar resumo"}</button></section>;
  const save = () => { artifactRepository.update(current.id, content); highlightRepository.list(chapterId).forEach((highlight) => { const resolved = resolveHighlight(content, highlight); highlightRepository.update(highlight.id, { ...resolved, summaryArtifactId: current.id }); }); historyRepository.add(chapterId, "summary_edited", "Resumo editado", { destination: "summary", resourceId: current.id }); setEditing(false); rerender((value) => value + 1); onStatus("Resumo salvo. Destaques sem âncora segura foram preservados como não localizados."); };
  const selectText = () => { const root = readerRef.current; const range = window.getSelection()?.rangeCount ? window.getSelection()!.getRangeAt(0) : null; if (!root || !range) return; const anchor = getSelectionAnchor(root, range, content); if (!anchor) return; if (hasOverlap(anchor, highlights)) { setSelection(undefined); onStatus("Esse trecho já possui uma marcação. Altere ou remova a marcação existente antes de sobrepor outra."); return; } setSelection(anchor); };
  const addHighlight = (color: Color) => { if (!selection) return; highlightRepository.add({ chapterId, ...selection, color, summaryArtifactId: current.id, status: "active" }); historyRepository.add(chapterId, "highlight_created", "Marcador criado", { destination: "summary", sourceText: selection.text }); window.getSelection()?.removeAllRanges(); setSelection(undefined); rerender((value) => value + 1); onStatus("Destaque salvo diretamente no resumo."); };
  const remove = (item: HighlightRecord) => { highlightRepository.remove(item.id); setActive(undefined); rerender((value) => value + 1); onStatus("Destaque removido."); };
  const updateHighlight = (item: HighlightRecord, patch: Partial<HighlightRecord>) => { const updated = highlightRepository.update(item.id, patch); if (updated) setActive(updated); rerender((value) => value + 1); };
  const setNote = (item: HighlightRecord) => { const note = window.prompt("Anotação vinculada ao trecho", item.note ?? ""); if (note === null) return; updateHighlight(item, { note: note.trim() || undefined }); onStatus("Anotação salva."); };
  const toggleFocus = () => setFocus((currentFocus) => { emitAryaVisualPreference({ focus: !currentFocus }); return !currentFocus; });
  return <section className={`settings-surface mt-5 p-5 sm:p-7 ${focus ? "fixed inset-0 z-50 m-0 overflow-y-auto rounded-none bg-[var(--bg-page)]" : ""}`}><header className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--border)] pb-5"><div><p className="text-xs font-semibold tracking-[.16em] text-[var(--accent)]">PÁGINAS ESCRITAS</p><h2 className="mt-1 font-serif text-3xl">Resumo do capítulo</h2></div><div className="flex flex-wrap gap-2"><button onClick={() => navigator.clipboard.writeText(content).then(() => onStatus("Resumo copiado."))} className="rounded-full border border-[var(--border-strong)] p-2.5" aria-label="Copiar resumo"><Copy size={16} /></button><button onClick={() => setPanel(true)} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm font-semibold">Ver destaques</button><button onClick={() => setEditing((value) => !value)} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm font-semibold"><Pencil className="mr-1 inline" size={15} />{editing ? "Ler" : "Editar"}</button><button onClick={onRegenerate} disabled={generating} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm font-semibold">{generating ? "Gerando..." : "Regenerar"}</button><button onClick={toggleFocus} className="rounded-full bg-[var(--button-primary)] px-3 py-2 text-sm font-semibold text-white">{focus ? <X className="inline" size={15} /> : <Expand className="mr-1 inline" size={15} />}{focus ? "Sair" : "Modo foco"}</button></div></header>{editing ? <><textarea value={content} onChange={(event) => setContent(event.target.value)} className="mt-6 min-h-[420px] w-full resize-y rounded-2xl bg-[var(--surface-soft)] p-5 leading-7 outline-none" /><div className="mt-4 text-right"><button onClick={save} className="rounded-full bg-[var(--button-primary)] px-5 py-2.5 text-sm font-semibold text-white"><Save className="mr-2 inline" size={15} />Salvar alterações</button></div></> : <><div className="relative"><SummaryText rootRef={readerRef} content={content} highlights={highlights} onSelect={selectText} onHighlight={setActive} />{selection && <SelectionToolbar selection={selection} onColor={addHighlight} onExplain={onExplainSelection} onClose={() => setSelection(undefined)} />}</div>{active && <HighlightActions item={active} onColor={(color) => updateHighlight(active, { color })} onNote={() => setNote(active)} onExplain={onExplainSelection} onRemove={() => remove(active)} />}</>}{panel && <HighlightsPanel highlights={highlights} onClose={() => setPanel(false)} onPick={(item) => { setActive(item); setPanel(false); }} />}</section>;
}

function SelectionToolbar({ selection, onColor, onExplain, onClose }: { selection: TextSelectionAnchor; onColor: (color: Color) => void; onExplain?: (text: string) => void; onClose: () => void }) { return <div className="sticky bottom-4 z-20 mx-auto mt-3 flex w-fit max-w-full flex-wrap items-center justify-center gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-2 shadow-[var(--shadow-medium)]"><Highlighter size={15} />{swatches.map((swatch) => <button key={swatch.color} onClick={() => onColor(swatch.color)} className={`size-8 rounded-full ${swatch.className} ring-offset-2 hover:ring-2 hover:ring-[var(--accent)]`} aria-label={`Destacar em ${swatch.label}`} />)}<button onClick={() => onExplain?.(selection.text)} className="rounded-full bg-[var(--button-primary)] px-3 py-2 text-sm font-semibold text-white">✨ Explicar</button><button onClick={onClose} className="p-2" aria-label="Fechar ações"><X size={16} /></button></div>; }
function HighlightActions({ item, onColor, onNote, onExplain, onRemove }: { item: HighlightRecord; onColor: (color: Color) => void; onNote: () => void; onExplain?: (text: string) => void; onRemove: () => void }) { return <div className="mt-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 shadow-[var(--shadow-soft)]"><p className="font-medium">“{item.text}”</p>{item.note && <p className="mt-2 text-sm text-[var(--text-secondary)]">{item.note}</p>}<div className="mt-3 flex flex-wrap gap-2">{swatches.map((swatch) => <button key={swatch.color} onClick={() => onColor(swatch.color)} className={`size-7 rounded-full ${swatch.className}`} aria-label={`Mudar para ${swatch.label}`} />)}<button onClick={onNote} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm"><StickyNote className="mr-1 inline" size={14} />Anotação</button><button onClick={() => onExplain?.(item.text)} className="rounded-full border border-[var(--border-strong)] px-3 py-2 text-sm"><MessageCircle className="mr-1 inline" size={14} />Explicar</button><button onClick={onRemove} className="rounded-full border border-red-300 px-3 py-2 text-sm text-red-700">Remover</button></div></div>; }
function HighlightsPanel({ highlights, onClose, onPick }: { highlights: HighlightRecord[]; onClose: () => void; onPick: (item: HighlightRecord) => void }) { const active = highlights.filter((highlight) => highlight.status !== "orphaned"); const orphaned = highlights.filter((highlight) => highlight.status === "orphaned"); return <aside className="fixed inset-y-0 right-0 z-[60] w-full max-w-md overflow-y-auto border-l border-[var(--border)] bg-[var(--surface)] p-6 shadow-2xl"><button onClick={onClose} className="float-right p-2" aria-label="Fechar destaques"><X /></button><h3 className="font-serif text-2xl">Destaques</h3><div className="mt-6 space-y-3">{active.length ? active.map((highlight) => <button key={highlight.id} onClick={() => onPick(highlight)} className="block w-full rounded-xl bg-[var(--surface-soft)] p-4 text-left"><mark className={swatches.find((swatch) => swatch.color === highlight.color)?.className}>{highlight.text}</mark>{highlight.note && <p className="mt-2 text-sm text-[var(--text-secondary)]">{highlight.note}</p>}</button>) : <p className="text-sm text-[var(--text-secondary)]">Nenhum trecho destacado ainda.</p>}{orphaned.length > 0 && <p className="pt-3 text-xs text-[var(--text-muted)]">{orphaned.length} destaque(s) foram preservados, mas não aparecem porque o trecho foi alterado e não pôde ser localizado com segurança.</p>}</div></aside>; }
function SummaryText({ rootRef, content, highlights, onSelect, onHighlight }: { rootRef: React.RefObject<HTMLDivElement | null>; content: string; highlights: HighlightRecord[]; onSelect: () => void; onHighlight: (item: HighlightRecord) => void }) { const visible = highlights.filter((item) => item.status !== "orphaned" && item.start !== undefined && item.end !== undefined).sort((first, second) => first.start! - second.start!); const segments: { text: string; highlight?: HighlightRecord }[] = []; let cursor = 0; visible.forEach((highlight) => { if (highlight.start! < cursor) return; if (highlight.start! > cursor) segments.push({ text: content.slice(cursor, highlight.start) }); segments.push({ text: content.slice(highlight.start, highlight.end), highlight }); cursor = highlight.end!; }); if (cursor < content.length) segments.push({ text: content.slice(cursor) }); if (!segments.length) segments.push({ text: content }); return <div ref={rootRef} onMouseUp={onSelect} className="summary-reader mt-6 whitespace-pre-wrap leading-8 text-[var(--text-primary)]">{segments.map((segment, index) => segment.highlight ? <button type="button" key={`${segment.highlight.id}-${index}`} onClick={() => onHighlight(segment.highlight!)} className={`${swatches.find((swatch) => swatch.color === segment.highlight?.color)?.className} rounded px-0.5 text-left decoration-current underline-offset-2`}>{segment.text}{segment.highlight.note && <StickyNote aria-label="Trecho com anotação" className="ml-1 inline text-[var(--accent-strong)]" size={13} />}</button> : <span key={index}>{segment.text}</span>)}</div>; }
