import assert from "node:assert/strict";
import { validateGeneratedQuiz, type GeneratedQuizPayload } from "../src/services/ai/quiz-validation.ts";
import { createTextSelectionAnchor, resolveHighlight } from "../src/features/study/highlight-anchors.ts";

type Question = GeneratedQuizPayload["questions"][number];
const labels = ["A", "B", "C", "D", "E"] as const;
const topics = ["assimilação", "acomodação", "equilibração", "esquemas mentais", "mediação pedagógica", "aprendizagem significativa", "desenvolvimento moral", "interação social", "avaliação formativa", "autonomia discente"];
const types: Question["questionType"][] = ["statements", "statements", "multiple_choice", "multiple_choice", "true_false_sequence", "assertion_reason", "assertion_reason", "association", "application", "application"];

function base(index: number, questionType: Question["questionType"]): Question {
  const topic = topics[index];
  const commands = ["Determine a consequência central de", "Compare o mecanismo descrito para", "Delimite o alcance teórico de", "Reconheça a condição que diferencia", "Identifique a implicação pedagógica de", "Examine a contribuição acadêmica de", "Relacione os critérios envolvidos em", "Distinga o papel contextual de", "Avalie a finalidade formativa de", "Justifique a importância prática de"];
  return { id: `q${index + 1}`, questionType, question: `${commands[index]} ${topic}, considerando exclusivamente as relações apresentadas no capítulo e a situação acadêmica descrita.`, options: labels.map((label) => ({ label, text: `Alternativa ${label} relacionada exclusivamente ao tópico ${topic}.` })), correctAnswer: labels[index % labels.length], explanation: `A alternativa correta é compatível com o tratamento de ${topic} no conteúdo de estudo e as demais alteram uma relação conceitual relevante.`, sourceReference: { text: `Trecho do material que explica ${topic}.`, section: `Tópico ${index + 1}: ${topic}` }, statements: null, assertion: null, reason: null, reasonJustifies: null, associationLeft: null, associationRight: null, scenario: null };
}

function statementQuestion(index: number): Question { const item = base(index, "statements"); item.question = index === 0 ? "Examine as afirmativas sobre assimilação e indique a combinação compatível com o percurso cognitivo apresentado no texto." : "Ao considerar acomodação diante de uma informação incompatível, analise as afirmativas e selecione a combinação sustentada pelo capítulo."; item.statements = ["A primeira afirmativa apresenta uma relação compatível com o texto.", "A segunda afirmativa apresenta uma consequência condicionada pelo contexto.", "A terceira afirmativa preserva a distinção conceitual estudada.", "A quarta afirmativa relaciona adequadamente o processo e seu efeito."]; item.options = [{ label: "A", text: "I e II, apenas." }, { label: "B", text: "I e III, apenas." }, { label: "C", text: "II e IV, apenas." }, { label: "D", text: "I, II e III, apenas." }, { label: "E", text: "I, II, III e IV." }]; return item; }
function trueFalseQuestion(index: number): Question { const item = base(index, "true_false_sequence"); item.question = `Considerando ${topics[index]} como foi apresentado no capítulo, classifique cada afirmativa como V (verdadeira) ou F (falsa) e assinale a sequência correta.`; item.statements = ["A primeira proposição reproduz uma ideia apresentada no texto.", "A segunda proposição inverte uma relação descrita no conteúdo.", "A terceira proposição mantém uma condição importante do conceito.", "A quarta proposição atribui uma consequência que o material não sustenta."]; item.options = [{ label: "A", text: "V – F – V – F" }, { label: "B", text: "F – V – V – F" }, { label: "C", text: "V – V – F – F" }, { label: "D", text: "F – F – V – V" }, { label: "E", text: "V – F – F – V" }]; return item; }
function assertionReasonQuestion(index: number): Question { const item = base(index, "assertion_reason"); item.question = index === 5 ? "Julgue a tese e a justificativa referentes à aprendizagem significativa, verificando se a segunda proposição fundamenta a primeira." : "Examine a proposição causal sobre desenvolvimento moral e decida se a razão apresentada explica adequadamente a asserção."; item.assertion = "I. A aprendizagem depende de relações conceituais que precisam ser interpretadas no contexto estudado."; item.reason = "II. O material demonstra que a compreensão do conceito exige reconhecer suas condições, e não apenas memorizar uma definição isolada."; item.reasonJustifies = true; item.options = [{ label: "A", text: "As asserções I e II são verdadeiras, e II justifica corretamente I." }, { label: "B", text: "As asserções I e II são verdadeiras, mas II não justifica I." }, { label: "C", text: "A asserção I é verdadeira, e II é falsa." }, { label: "D", text: "A asserção I é falsa, e II é verdadeira." }, { label: "E", text: "As asserções I e II são falsas." }]; return item; }
function associationQuestion(index: number): Question { const item = base(index, "association"); item.question = `Associe os conceitos relacionados a ${topics[index]} às respectivas descrições apresentadas no material e assinale a sequência correta.`; item.associationLeft = [{ id: "1", text: "Conceito de origem" }, { id: "2", text: "Processo relacionado" }, { id: "3", text: "Resultado esperado" }]; item.associationRight = [{ id: "A", text: "Descrição do processo relacionado." }, { id: "B", text: "Descrição do resultado esperado." }, { id: "C", text: "Descrição do conceito de origem." }]; item.options = [{ label: "A", text: "1-C, 2-A, 3-B" }, { label: "B", text: "1-A, 2-C, 3-B" }, { label: "C", text: "1-B, 2-A, 3-C" }, { label: "D", text: "1-C, 2-B, 3-A" }, { label: "E", text: "1-A, 2-B, 3-C" }]; return item; }
function applicationQuestion(index: number): Question { const item = base(index, "application"); item.question = index === 8 ? "Diante do caso pedagógico descrito, escolha a decisão avaliativa que mantém coerência com os critérios formativos estudados." : "Em uma atividade de estudo autônomo, identifique a conduta que melhor traduz a construção progressiva de responsabilidade da estudante."; item.scenario = index === 8 ? "Uma docente acompanha produções parciais, devolve comentários sobre critérios previamente discutidos e reorganiza a próxima atividade conforme as dificuldades observadas. Ela precisa escolher uma ação coerente com os princípios desenvolvidos no capítulo." : "Uma estudante recebe um objetivo complexo, planeja as etapas de leitura, monitora suas dúvidas e revisa a estratégia quando percebe que uma interpretação inicial não foi suficiente. A orientação precisa se apoiar somente nas relações descritas no conteúdo."; return item; }
function fixture(): GeneratedQuizPayload { return { questions: types.map((type, index) => type === "statements" ? statementQuestion(index) : type === "true_false_sequence" ? trueFalseQuestion(index) : type === "assertion_reason" ? assertionReasonQuestion(index) : type === "association" ? associationQuestion(index) : type === "application" ? applicationQuestion(index) : base(index, type)) }; }
function mustReject(mutator: (quiz: GeneratedQuizPayload) => void, label: string) { const value = fixture(); mutator(value); assert.equal(validateGeneratedQuiz(value).success, false, label); }

const valid = fixture(); const accepted = validateGeneratedQuiz(valid); if (!accepted.success) console.error(accepted.error.issues); assert.equal(accepted.success, true, "fixture com todos os formatos deve ser aceita");
assert.equal(validateGeneratedQuiz({ questions: valid.questions.slice(0, 9) }).success, false, "9 questões devem ser rejeitadas");
mustReject((quiz) => { quiz.questions[0].options = quiz.questions[0].options.slice(0, 4); }, "4 alternativas devem ser rejeitadas");
mustReject((quiz) => { quiz.questions.forEach((question) => { question.questionType = "multiple_choice"; }); }, "formatos repetidos devem ser rejeitados");
mustReject((quiz) => { quiz.questions[0].statements = quiz.questions[0].statements!.slice(0, 3); }, "statements com três afirmativas deve ser rejeitada");
mustReject((quiz) => { quiz.questions[4].options[0].text = "V – F – V"; }, "sequência V/F com três posições deve ser rejeitada");
mustReject((quiz) => { quiz.questions[5].reason = null; }, "asserção e razão sem a razão deve ser rejeitada");
mustReject((quiz) => { quiz.questions[7].associationRight = null; }, "associação sem definições deve ser rejeitada");
mustReject((quiz) => { quiz.questions[7].options[0].text = "1-D, 2-A, 3-B"; }, "associação com referência inexistente deve ser rejeitada");
mustReject((quiz) => { quiz.questions[8].scenario = null; }, "aplicação sem situação deve ser rejeitada");
console.log("Quiz fixtures: schemas especializados, diversidade e casos inválidos aprovados.");

const summary = "## 📚 Título\nA assimilação acontece com acentos e emoji 🧠.\n\n**Uma frase em negrito** permanece estudável."; const phraseStart = summary.indexOf("assimilação"); const anchor = createTextSelectionAnchor(summary, phraseStart, phraseStart + "assimilação".length)!; const record = { id: "highlight-1", chapterId: "chapter-1", color: "yellow" as const, createdAt: "2026-01-01", ...anchor };
assert.equal(resolveHighlight(summary, record).status, "active", "acentos, emoji e quebra de linha devem manter a âncora"); assert.equal(resolveHighlight("Introdução nova. " + summary, record).status, "active", "um trecho único deve ser reencontrado após edição"); const duplicatedSummary = "assimilação sem contexto. " + summary; assert.equal(resolveHighlight(duplicatedSummary, record).status, "active", "o contexto deve diferenciar ocorrências próximas"); assert.equal(resolveHighlight(duplicatedSummary, { ...record, prefix: undefined, suffix: undefined }).status, "orphaned", "trecho repetido sem âncora contextual não pode ser marcado silenciosamente"); console.log("Highlights fixtures: âncoras, acentos, emoji, edição e órfãos aprovados.");
