"use client";

import { useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { BrainCircuit, Check, MoreHorizontal, PenLine, RotateCcw, Search, Sparkles, Sprout } from "lucide-react";
import { NewSubjectDialog, type LocalSubjectDraft } from "@/components/forms/new-subject-dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { emitAryaEvent } from "@/components/arya/arya-state";
import { chapterRepository } from "@/services/repositories/chapter-repository";
import { subjectRepository } from "@/services/repositories/subject-repository";
import { getChapterStudyProgress } from "@/features/dashboard/dashboard-data";

const shell = "rounded-[28px] border border-[var(--card-border)] bg-[var(--card-bg)] p-6 shadow-[0_14px_35px_var(--shadow-soft)] backdrop-blur-xl sm:p-8";
const title = (eyebrow: string, heading: string, description: string) => <header><p className="text-sm font-semibold text-[var(--accent)]">{eyebrow}</p><h1 className="mt-2 font-serif text-3xl font-semibold">{heading}</h1><p className="mt-2 text-sm text-[var(--muted)]">{description}</p></header>;

type LibrarySubject = { title: string; slug: string; chapters: number; progress: number; access: string; tone: string };
const coverPaths = ["/books/aryaverse-collection/unit-01.png", "/books/aryaverse-collection/unit-02.png", "/books/aryaverse-collection/unit-03.png"];

function dateLabel(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)); }
function readSubjects(): LibrarySubject[] { return subjectRepository.list().filter((item) => !item.archived).map((item) => { const chapters = chapterRepository.list(item.id); return { title: item.name, slug: item.id, chapters: chapters.length, progress: Math.min(100, chapters.reduce((total, chapter) => total + getChapterStudyProgress(chapter), 0)), access: dateLabel(item.updatedAt), tone: item.coverColor }; }); }

export function LibraryExperience() {
  const router = useRouter(); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [subjects, setSubjects] = useState<LibrarySubject[]>(readSubjects); const [dialogOpen, setDialogOpen] = useState(false); const [menu, setMenu] = useState<string>(); const [opening, setOpening] = useState<string>();
  const visible = subjects.filter((subject) => subject.title.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || filter === "in-progress" && subject.progress < 70 || filter === "advanced" && subject.progress >= 70));
  const saveSubject = (draft: LocalSubjectDraft) => { const wasEmpty = subjects.length === 0; subjectRepository.save({ name: draft.title.trim(), description: draft.description, coverColor: draft.tone, icon: draft.icon, visualTheme: draft.visualTheme, archived: false }); setSubjects(readSubjects()); if (wasEmpty) emitAryaEvent("FIRST_SUBJECT_CREATED"); };
  const rename = (subject: LibrarySubject) => { const value = window.prompt("Nome do livro", subject.title); if (!value?.trim()) return; subjectRepository.rename(subject.slug, value.trim()); setSubjects(readSubjects()); setMenu(undefined); };
  const openBook = (subject: LibrarySubject) => { if (opening) return; setOpening(subject.slug); window.setTimeout(() => { router.push(`/biblioteca/${subject.slug}`); }, 620); };
  return <div>{title("BIBLIOTECA VIVA", "Sua estante de matérias e estudos.", "Cada livro reúne capítulos, anotações e tudo o que você vem descobrindo.")}<div className="mt-7 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-3 text-[var(--muted)]" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar uma matéria" className="w-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] py-3 pl-11 pr-4 text-sm outline-none focus:border-[var(--accent)]" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none"><option value="all">Todos os livros</option><option value="in-progress">Em cultivo</option><option value="advanced">Mais avançados</option></select><button onClick={() => setDialogOpen(true)} className="rounded-2xl bg-[var(--button-primary)] px-5 py-3 text-sm font-semibold text-white shadow-lg">Nova matéria</button></div>{visible.length ? <div className={`${shell} relative mt-6 grid grid-cols-1 gap-7 sm:grid-cols-2 xl:grid-cols-3`}>{visible.map((subject, index) => <div key={subject.slug} className="relative"><Book subject={subject} cover={coverPaths[index % coverPaths.length]} opening={opening === subject.slug} onOpen={() => openBook(subject)} /><button onClick={() => setMenu(menu === subject.slug ? undefined : subject.slug)} className="absolute right-3 top-3 z-20 rounded-full bg-white/90 p-1.5 shadow" aria-label={`Ações de ${subject.title}`}><MoreHorizontal size={16} /></button>{menu === subject.slug && <div className="absolute right-3 top-12 z-30 w-40 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-2 text-sm shadow-lg"><button onClick={() => openBook(subject)} className="block w-full rounded-lg px-2 py-1.5 text-left hover:bg-[var(--surface-soft)]">Abrir</button><button onClick={() => rename(subject)} className="block w-full rounded-lg px-2 py-1.5 text-left hover:bg-[var(--surface-soft)]">Renomear</button><button onClick={() => { if (window.confirm(`Excluir ${subject.title}?`)) { subjectRepository.remove(subject.slug); setSubjects(readSubjects()); } }} className="block w-full rounded-lg px-2 py-1.5 text-left text-red-700 hover:bg-red-50">Excluir</button></div>}</div>)}</div> : <div className="mt-6"><EmptyState message="Sua biblioteca está esperando sua primeira matéria." action="Criar nova matéria" onAction={() => setDialogOpen(true)} /></div>}{dialogOpen && <NewSubjectDialog onClose={() => setDialogOpen(false)} onSave={saveSubject} />}</div>;
}

function Book({ subject, cover, opening, onOpen }: { subject: LibrarySubject; cover: string; opening: boolean; onOpen: () => void }) { return <button type="button" onClick={onOpen} className={`library-cover ${opening ? "library-cover-opening" : ""}`} aria-label={`Abrir o livro ${subject.title}`}><Image src={cover} alt="" fill sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover" priority={false} /><span className="library-cover-shade" /><span className="library-cover-medallion"><strong style={{ fontFamily: '"Palatino Linotype", "Book Antiqua", Georgia, serif', fontSize: "clamp(.78rem, 1vw, .96rem)", lineHeight: 1.18, letterSpacing: ".02em" }}>{subject.title}</strong><small>{subject.chapters} capítulos · {subject.progress}%</small><em>Último acesso: {subject.access}</em></span><Sparkles className="library-cover-sparkle" size={18} /></button>; }

export function SummariesExperience() { const [compact, setCompact] = useState(false); return <div>{title("PAGINAS ESCRITAS", "Resumos que a Arya guardou para voce.", "Leituras transformadas em paginas claras para revisitar quando precisar.")}<div className={`${shell} mt-7`}><div className="flex items-center justify-between"><h2 className="font-serif text-xl">Neuroplasticidade e aprendizagem</h2><button onClick={() => setCompact(!compact)} className="text-sm font-semibold text-[var(--accent-deep)]">{compact ? "Ler completo" : "Modo breve"}</button></div><p className="mt-5 leading-7 text-[var(--muted)]">A neuroplasticidade descreve a capacidade do cerebro de se reorganizar ao longo das experiencias e da aprendizagem.</p>{!compact && <><h3 className="mt-6 font-semibold">Ideias que merecem ficar</h3><ul className="mt-3 space-y-3 text-sm text-[var(--muted)]"><li>- Experiencias e pratica estimulam novas conexoes.</li><li>- A aprendizagem pode modificar circuitos neuronais.</li><li>- A revisao fortalece o que ja foi construido.</li></ul></>}</div></div>; }

export function FlashcardsExperience() { const [revealed, setRevealed] = useState(false); return <div>{title("ESTUDOS", "Um conceito de cada vez.", "Vire a pagina e deixe a lembranca encontrar voce.")}<button onClick={() => setRevealed(!revealed)} className={`${shell} mt-7 min-h-72 w-full text-left transition hover:-translate-y-1`}><span className="text-sm font-semibold text-[var(--accent)]">FLASHCARD 01 / 20</span><h2 className="mt-8 font-serif text-3xl">{revealed ? "Capacidade do cerebro de se reorganizar a partir das experiencias." : "O que e neuroplasticidade?"}</h2><span className="mt-12 flex items-center gap-2 text-sm text-[var(--muted)]"><RotateCcw size={16} />Toque para {revealed ? "ver a pergunta" : "revelar a resposta"}</span></button></div>; }

export function MindMapsExperience() { return <div>{title("JORNADAS DE IDEIAS", "Veja como seus conceitos se conectam.", "Um mapa vivo para seguir o fio de cada assunto.")}<section className={`${shell} mt-7 overflow-auto`}><div className="min-w-[580px] py-8 text-center"><div className="mind-node mx-auto">Neuroplasticidade</div><div className="mind-line mx-auto" /><div className="flex justify-around"><div><div className="mind-node">Experiencias</div><div className="mt-6 text-sm text-[var(--muted)]">pratica<br />ambiente<br />aprendizagem</div></div><div><div className="mind-node">Transformacoes</div><div className="mt-6 text-sm text-[var(--muted)]">conexoes<br />adaptacao<br />memoria</div></div><div><div className="mind-node">Revisao</div><div className="mt-6 text-sm text-[var(--muted)]">fortalecimento<br />consolidacao<br />dominio</div></div></div></div></section></div>; }

export function QuizzesExperience() { const [answered, setAnswered] = useState<number | null>(null); const choices = ["A capacidade de memorizar fatos sem pratica.", "A reorganizacao do cerebro a partir de experiencias.", "Um tipo de avaliacao escolar.", "A repeticao de uma materia."]; return <div>{title("AVALIACOES", "Uma pausa para perceber o que floresceu.", "Arya preparou perguntas apenas com base nos seus estudos.")}<section className={`${shell} mt-7`}><span className="text-sm font-semibold text-[var(--accent)]">QUESTAO 1 DE 10</span><h2 className="mt-4 font-serif text-2xl">Como o estudo descreve a neuroplasticidade?</h2><div className="mt-6 grid gap-3">{choices.map((choice, index) => <button key={choice} onClick={() => setAnswered(index)} className={`rounded-2xl border p-4 text-left text-sm transition ${answered === index ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--card-border)] hover:bg-[var(--surface-soft)]"}`}>{String.fromCharCode(65 + index)}. {choice}{answered === index && <Check className="float-right" size={17} />}</button>)}</div></section></div>; }

export function DiaryExperience() { const [note, setNote] = useState(""); return <div>{title("DIARIO", "Uma pagina para o que voce percebeu.", "Anotacoes pessoais acompanham cada parte da sua jornada.")}<section className={`${shell} mt-7`}><label className="text-sm font-semibold text-[var(--accent)]">6 DE AGOSTO</label><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Hoje descobri que..." className="mt-5 min-h-56 w-full resize-none bg-transparent font-serif text-xl leading-8 outline-none placeholder:text-[var(--text-muted)]" /><div className="flex justify-between border-t border-[var(--card-border)] pt-4 text-sm text-[var(--muted)]"><span>{note.length} caracteres</span><button className="font-semibold text-[var(--accent-deep)]"><PenLine className="mr-1 inline" size={15} />Guardar pagina</button></div></section></div>; }

export function JourneysExperience() { return <div>{title("JORNADAS", "Os caminhos que voce escolheu cultivar.", "Volte para uma trilha ou comece uma nova exploracao.")}<div className="mt-7 grid gap-4 md:grid-cols-2"><JourneyCard icon={Sprout} name="Fundamentos de Pedagogia" detail="5 capitulos ao seu ritmo" progress="72%" /><JourneyCard icon={BrainCircuit} name="Psicologia da Educacao" detail="3 capitulos em descoberta" progress="46%" /></div></div>; }
function JourneyCard({ icon: Icon, name, detail, progress }: { icon: typeof Sprout; name: string; detail: string; progress: string }) { return <article className={shell}><Icon className="text-[var(--accent)]" size={23} /><h2 className="mt-5 font-serif text-xl">{name}</h2><p className="mt-2 text-sm text-[var(--muted)]">{detail}</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-[var(--surface-soft)]"><i className="block h-full w-2/3 rounded-full bg-[var(--accent)]" /></div><p className="mt-2 text-xs text-[var(--muted)]">{progress} de caminho percorrido</p></article>; }

export function CalendarExperience() { return <div>{title("CALENDARIO", "Tempo para aprender, tempo para respirar.", "Suas revisoes encontram espaco na semana sem apertar sua rotina.")}<section className={`${shell} mt-7`}><div className="grid grid-cols-7 gap-2 text-center text-sm">{["S", "T", "Q", "Q", "S", "S", "D"].map((day, index) => <div key={`${day}${index}`}><p className="mb-3 text-xs text-[var(--muted)]">{day}</p><button className={`grid size-10 place-items-center rounded-full ${index === 3 ? "bg-[var(--accent)] text-white shadow-lg" : "hover:bg-[#eef4e9]"}`}>{index + 4}</button>{index === 3 && <i className="mx-auto mt-2 block size-1.5 rounded-full bg-[#c79e55]" />}</div>)}</div><div className="mt-8 rounded-2xl bg-[#edf4e8] p-4 text-sm"><strong>Hoje:</strong> revisar Neuroplasticidade em 12 minutos.</div></section></div>; }
